### ISSUE TITLE
how do i change minecraft version

### ISSUE THREAD

**Issue by Eeeevox** [Kichura/Minecraft_ARM#3]
I know that may sound kinda silly but how do I change minecraft version i'm stuck at 1.20.4 but there's almost none neoforge documantion for that version.

**Comment by Eeeevox** [comment]
Ok, I fixed it so heres the tutorial 
1) click on the minecraft ARM instalation in your prism launcher
2) on the side bar click the `_edit_` option
3) then click on the _`Version`_ tab right below the _`Minecraft log`_ 
4) select on the `_Minecraft_` option
5) in the top right corner there should be an _`Change version`_
6) select your preferd version
7) boot your game and enjoy!~

**Comment by Kichura** [comment]
> I know that may sound kinda silly but how do I change minecraft version i'm stuck at 1.20.4 but there's almost none neoforge documantion for that version.

The reason why i do not have a neoforge/fabric/etc documentation put up is because this project does not focus on modded in general, hence why it's left out.
